---
- name: install aur packages
  become: no
  kewlfft.aur.aur:
    state: present
    use: makepkg
    name:
      - ttf-impallari-cabin-font  # cv font
      - nerd-fonts-jetbrains-mono # coding font
      - glow                      # render markdown cli
      - downgrade                 # downgrade packages
      - asdf-vm                   # ASDF tools versions manager
      - conftest                  # config tester
      - downgrade                 # downgrade packages
      - powershell-bin            # powershell for Linux (used in VScode)
      - pdk                       # Puppet Development Kit
      - tflint                    # a Terraform linter

- name: install base packages
  pacman:
    name:
      # Main
      - noto-fonts         # unicode font
      # Shell
      - fish               # powerful shell
      - zsh
      - starship           # cross-shell prompt
        # Tools
      - git                #
      - exa                # powerful ls
      - bc                 # maths
      - jq                 # json processor
      - most               # colorized pager
      - bat                # colorized cat
      - neovim             # future of vim
      - tree               #
      - vim                #
      - man                #
      - tmux               # terminal multiplexer
      - asciinema          # term recorder
      - expect             # automation tool
      - arch-audit         # list vulnerabilities
      # System
      - htop               # system monitor
      - net-tools          # netstat
      - reflector          # mirror sorter
      - nmap               # port scanner
      - tcpdump            # packet analyzer
      - whois              # query registry
      - stress             # stress test tool
      # Disk
      - iotop              # disk "top"
      - ncdu               # disk usage analyzer
      # Network
      - nethogs            # net "top"
      - openssh            #
      - keychain           # ssh-agent wrapper
      - wget               # downloader
      - bind-tools         # dns tools
      - openbsd-netcat     # network utility
      - speedtest-cli      #
      # Utils
      - cronie             # Scheduler
      - at                 # Scheduler
      - rsync              # sync tool
      - words              # dictionnaries
      - fzf                # fuzzy finder
      - neofetch           #
      - unzip              # uncompress zip
      - cifs-utils         #
      - shellcheck         # sh linter
      - oath-toolkit       # otp tool
      - dmidecode          # dump dmi table content
      - python-pre-commit  # pre-commit hook manager
        # python development
      - mypy               # Python static type checker
      - python-black       # Python linter
      - python-pip         # python3 package manager
      - python-poetry      # Modern Python build solution
      - puppet             # Puppet
      - graphviz           # graphs vizualiser
    state: present

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'

- name: set timezone
  shell: timedatectl set-timezone Europe/Paris

- name: set ntp
  shell: timedatectl set-ntp true
