---
- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'
    - blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist

- name: Update lists and upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Configure reflector
  copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/
  notify: enable reflector

- name: Install pacman hooks
  pacman:
    name:
      - kernel-modules-hook # keep kernel modules dir after an upgrade

- name: Enable kernel modules cleanup
  systemd:
    name: linux-modules-cleanup
    enabled: yes
