---
- hosts: all
  become: yes

  vars:
    user: user
    shell: /usr/bin/fish

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

  roles:
    - { role: pacman, tags: pacman }
    - { role: base, tags: base }
    - { role: aur, tags: aur }
    - { role: containers, tags: containers }

